-- MySQL Script generated by MySQL Workbench
-- lun 09 may 2016 10:43:29 WEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sharis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sharis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sharis` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `sharis` ;

-- -----------------------------------------------------
-- Table `sharis`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharis`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nick` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `cumpleanos` DATETIME NULL,
  `telefono` INT(9) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ucs2
COLLATE = ucs2_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
